apiVersion : apps/v1
kind: Deployment
metadata:
  name: "jrkubcls01-14d7"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "jrkubcls01-14d7"
  template:
    metadata:
      labels:
        app: "jrkubcls01-14d7"
    spec:
      containers:
        - name: "jrkubcls01-14d7"
          image: "jasonsrealm.azurecr.io/jrkubcls01"
          ports:
          - containerPort: 80