on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jasonsrealm.azurecr.io
        username: ${{ secrets.acr_jasonsrealm_username }}
        password: ${{ secrets.acr_jasonsrealm_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t jasonsrealm.azurecr.io/jrkubcls01:${{ github.sha }}
        docker push jasonsrealm.azurecr.io/jrkubcls01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jrkubcls01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jrkubcls01858c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jrkubcls01858c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jrkubcls01858c
        container-registry-url: jasonsrealm.azurecr.io
        container-registry-username: ${{ secrets.acr_jasonsrealm_username }}
        container-registry-password: ${{ secrets.acr_jasonsrealm_password }}
        secret-name: jrkubcls01dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: jrkubcls01858c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          jasonsrealm.azurecr.io/jrkubcls01:${{ github.sha }}
        imagepullsecrets: |
          jrkubcls01dockerauth